---
title: "Challenge 2: Spicing things up with ggplot2"
author: "Eva Moylan"
date: "10/9/24"
format: html
editor: source
embed-resources: true
code-tools: true
echo: true
code-fold: true
self-contained: true
theme: sandstone
---

# Hot: Exploring `ggplot2` Annotation

## Set up dataset

```{r}
#| label: setup
#| output: false

#Load packages
library(tidyverse)
library(here)
library(dplyr)

#Load in data
surveys <- read_csv(here("data","surveys.csv"))

#Preview data, did it load correctly?
print(surveys) #yes! (removed from final output for visuals)

```

## Group data to find unique genera

```{r}
#| label: surveys-genera
#| message: false

#Find each species' genus
surveys |>
  group_by(genus,species)|> #group by genus to see corresponding species
  summarize() #tibble shows unique values 

```

## Plot weight across species

```{r}
#| label: boxplot

# A vector of a RG color deficient friendly palette with gray:
cdPalette_grey <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

#Box plot to compare weight within species
ggplot(data = surveys,
       mapping = aes(x = weight,
                     y = species,
                     color = genus)) +
  geom_boxplot() + #Remove plotting all the points here; clutters the plot
  scale_color_manual(values = cdPalette_grey) + 
  annotate("text", y = 1:14, x = 325, label = c("Neotoma", #N. abigula
                                                "Chaetodipus", #C. baileyi
                                                "Peromyscus", #P. eremicus
                                                "Perognathus", #P. flavus
                                                "Reithrodontomys", #R. fulvencens
                                                "Sigmodon", #S. hispidus
                                                "Onychomys", #O. leucogaster
                                                "Peromyscus", #P. maniculatus
                                                "Reithrodontomys", #R. megalotis
                                                "Dipodomys", #D. merriami
                                                "Dipodomys", #D. ordii
                                                "Chaetodipus", #C. penicillatus
                                                "Dipodomys", #O. spectabilis
                                                "Onychomys")) + #O. torridus
  theme_bw() + 
  scale_x_continuous(limits = c(0, 350)) + #Neotoma gets cut off so expand x-axis limit
  labs(x = "Weight (g)",
       y = NULL,
       subtitle = "Annotations represent genera",
       title = "Rodent Weight Across Species") +
  theme(legend.position = "none") 

```
